const {Router}=require("express")
const {alldata, adddata, signup, login, ui, loginpage, signuppage, reset, resetpass } = require("../controllers/user.controller")
const check = require("../middlewears/signup")
const passport = require("passport")
const { auth } = require("../middlewears/auth")
const router=Router()

router.get("/",alldata)
router.post("/",adddata)
router.post("/signup",check,signup)
router.get("/signup",signuppage)
router.get("/login",loginpage)
router.post("/login",passport.authenticate("local"),login)
router.get("/ui",ui)
router.get("/user",auth,(req,res)=>{
    res.status(200).send(req.user)
})
router.post("/otp",reset)
router.post("/reset",resetpass)
module.exports=router